/// CompanyEntity.swift
/// generated by jsonschema2swift

import Foundation
import SwiftyJSON


/// company
///
/// 会社
public struct CompanyEntity: EntityType {

  /// 会社の種類
  enum CompanyType: Int {
    case kabushiki = 1
    case goudou = 2
    case goumei = 3
    case goushi = 4
  }

  /// 会社名
  var name: String
  /// 会社ID
  var id: Int
  /// 住所
  var address: String
  /// 電話番号
  /// - pattern: ^[0-9]{2,5}-?[0-9]{1,4}-?[0-9]{4}$
  var tel: String?
  /// 上場企業かどうか
  var listedFlag: Bool?
  /// 会社の種類
  var companyType: CompanyType
  /// 会社URL
  var url: String?

  public init?(json: JSON) {
    guard !json.isEmpty else {
      return nil
    }
    self.name = json["name"].string!
    self.id = json["id"].int!
    self.address = json["address"].string!
    self.tel = json["tel"].string
    self.listedFlag = json["listed_flag"].bool
    self.companyType = CompanyType(rawValue: json["company_type"].integer!)!
    self.url = json["url"].string
  }

  static func ==(left: CompanyEntity, right: CompanyEntity) -> Bool {
    return left.id == right.id

  }

  var serialized: [String: Any] {
    var param: [String: Any] = [:]
    param["name"] = name.serialized
    param["id"] = id.serialized
    param["address"] = address.serialized
    param["tel"] = tel?.serialized
    param["listedFlag"] = listedFlag?.serialized
    param["companyType"] = companyType.serialized
    param["url"] = url?.serialized
    return param
  }
}
