/// CompanyClubEntity.swift
/// generated by jsonschema2swift

import Foundation
import SwiftyJSON


/// company_club
public struct CompanyClubEntity: RelatedEntityType {

  /// クラブ名
  public var name: String

  public var users: [UserEntity]

  public init(name: String, users: [UserEntity]) {
    self.name = name
    self.users = users
  }

  public init?(json: JSON) {
    if json.isEmpty {
      return nil
    }
    self.name = json["name"].string!
    self.users = json["users"].array!.map { UserEntity(json: $0)! } as [UserEntity]
  }

  var serialized: [String: Any] {
    var param: [String: Any] = [:]
    param["name"] = name.serialized
    param["users"] = users.serialized
    return param
  }
}
