/// CompanyResponseEntity.swift
/// generated by jsonschema2swift

import Foundation
import SwiftyJSON

/// company
///
/// 会社
public struct CompanyResponseEntity: ResponseEntityType {

  /// 会社
  var data: CompanyEntity?

  public init?(json: JSON) {
    guard !json.isEmpty else {
      return nil
    }
    self.data = CompanyEntity(json: json["data"]) as CompanyEntity?
  }

  var serialized: [String: Any] {
    var param: [String: Any] = [:]
    param["data"] = data?.serialized
    return param
  }
}
