/// CompanyResponsesEntity.swift
/// generated by jsonschema2swift

import Foundation
import SwiftyJSON


public struct CompanyResponsesEntity: ResponseEntityType {


  var data: [CompanyEntity]?

  public init?(json: JSON) {
    guard !json.isEmpty else {
      return nil
    }
    self.data = json["data"].arrayValue.map { CompanyEntity(json: $0)! } as [CompanyEntity]?
  }

  var serialized: [String: Any] {
    var param: [String: Any] = [:]
    param["data"] = data?.serialized
    return param
  }
}
