/// DepartmentEntity.swift
/// generated by jsonschema2swift

import Foundation
import SwiftyJSON


/// department
///
/// 部署
public struct DepartmentEntity: SingleEntityType {

  /// 部署ID
  public var id: Int
  /// 部署名
  public var name: String
  /// 会社ID
  public var companyId: Int

  public init(id: Int, name: String, companyId: Int) {
    self.id = id
    self.name = name
    self.companyId = companyId
  }

  public init?(json: JSON) {
    if json.isEmpty {
      return nil
    }
    self.id = json["id"].int!
    self.name = json["name"].string!
    self.companyId = json["company_id"].int!
  }

  public static func ==(left: DepartmentEntity, right: DepartmentEntity) -> Bool {
    return left.company_id == right.company_id
      && left.name == right.name

  }

  var serialized: [String: Any] {
    var param: [String: Any] = [:]
    param["id"] = id.serialized
    param["name"] = name.serialized
    param["company_id"] = companyId.serialized
    return param
  }
}
