/// DepartmentEntity.swift
/// generated by jsonschema2swift

import Foundation
import SwiftyJSON


/// department
///
/// 部署
public struct DepartmentEntity: EntityType {

  /// 部署ID
  var id: Int
  /// 部署名
  var name: String
  /// 会社ID
  var companyId: Int

  public init?(json: JSON) {
    guard !json.isEmpty else {
      return nil
    }
    self.id = json["id"].int!
    self.name = json["name"].string!
    self.companyId = json["company_id"].int!
  }

  static func ==(left: DepartmentEntity, right: DepartmentEntity) -> Bool {
    return left.company_id == right.company_id
 && left.name == right.name

  }

  var serialized: [String: Any] {
    var param: [String: Any] = [:]
    param["id"] = id.serialized
    param["name"] = name.serialized
    param["companyId"] = companyId.serialized
    return param
  }
}
