/// RoleEntity.swift
/// generated by jsonschema2swift

import Foundation
import SwiftyJSON


/// role
///
/// 役職
public struct RoleEntity: SingleEntityType {

  /// 役職名
  public enum Name: String {
    case staff = "一般社員"
    case projectGeneralManager = "主査"
    case supervisor = "主任"
    case sectionHead = "係長"
    case chiefEditor = "主幹"
    case secretary = "参事"
    case assistantSectionChief = "課長代理"
    case sectionChief = "課長"
    case assistantGeneralManager = "次長"
    case assistantManager = "部長代理"
    case viceManager = "副部長"
    case manager = "部長"
    case generalManager = "本部長"
    case counselor = "参与"
    case corporateOfficer = "執行役"
    case auditor = "監査役"
    case director = "取締役"
    case vicePresident = "副社長"
    case president = "社長"
    case chairman = "会長"
  }

  /// 役職名
  public var name: RoleEntity.Name?

  public init(name: RoleEntity.Name? = nil) {
    self.name = name
  }

  public init?(json: JSON) {
    if json.isEmpty {
      return nil
    }
    self.name = RoleEntity.Name(rawValue: json["name"].string!)
  }

  public static func ==(left: RoleEntity, right: RoleEntity) -> Bool {
    return left.name == right.name

  }

  var serialized: [String: Any] {
    var param: [String: Any] = [:]
    param["name"] = name?.serialized
    return param
  }
}
