/// UserResponseEntity.swift
/// generated by jsonschema2swift

import Foundation
import SwiftyJSON

/// user
///
/// ユーザ
public struct UserResponseEntity: ResponseEntityType {

  /// ユーザ
  var data: UserEntity?

  public init?(json: JSON) {
    guard !json.isEmpty else {
      return nil
    }
    self.data = UserEntity(json: json["data"]) as UserEntity?
  }

  var serialized: [String: Any] {
    var param: [String: Any] = [:]
    param["data"] = data?.serialized
    return param
  }
}
