/// UserEntity.swift
/// generated by jsonschema2swift

import Foundation
import SwiftyJSON


/// user
///
/// ユーザ
public struct UserEntity: RelatedEntityType {

  /// 社員名
  public var name: String
  /// メールアドレス
  public var email: String
  /// 社員ID
  public var id: Int
  /// 所属部署
  public var departments: [UserDepartmentEntity]
  /// 会社
  public var company: CompanyEntity

  public var userProfile: UserProfileEntity?

  public init(name: String, email: String, id: Int, departments: [UserDepartmentEntity], company: CompanyEntity, userProfile: UserProfileEntity? = nil) {
    self.name = name
    self.email = email
    self.id = id
    self.departments = departments
    self.company = company
    self.userProfile = userProfile
  }

  public init?(json: JSON) {
    if json.isEmpty {
      return nil
    }
    self.name = json["name"].string!
    self.email = json["email"].string!
    self.id = json["id"].int!
    self.departments = json["departments"].array!.map { UserDepartmentEntity(json: $0)! } as [UserDepartmentEntity]
    self.company = CompanyEntity(json: json["company"]) as CompanyEntity!
    self.userProfile = UserProfileEntity(json: json["user_profile"]) as UserProfileEntity?
  }

  public static func ==(left: UserEntity, right: UserEntity) -> Bool {
    return left.id == right.id

  }

  var serialized: [String: Any] {
    var param: [String: Any] = [:]
    param["name"] = name.serialized
    param["email"] = email.serialized
    param["id"] = id.serialized
    param["departments"] = departments.serialized
    param["company"] = company.serialized
    param["user_profile"] = userProfile?.serialized
    return param
  }
}
