/// UserProfileParamsEntity.swift
/// generated by jsonschema2swift

import Foundation
import SwiftyJSON


/// user_profile_params
public struct UserProfileParamsEntity: EntityType {

  /// 身長
  var height: Double?
  /// プロフィール投稿画像（jpeg、gif、pngだけ）
  var image: Image?
  /// 入社日
  var registedAt: Date?
  /// 所属クラブ
  var clubs: [String]?
  /// 体重
  var weight: Double?
  /// TOEICのスコア
  var toeicScore: Int?
  /// 生年月日
  var birthday: Date?

  public init?(json: JSON) {
    guard !json.isEmpty else {
      return nil
    }
    self.height = json["height"].double
    self.image = json["image"].image
    self.registedAt = Date.generateFromAPIFormat(string: json["registed_at"].string)
    self.clubs = json["clubs"].arrayValue.map { String(json: $0)! } as? [String]
    self.weight = json["weight"].double
    self.toeicScore = json["toeic_score"].int
    self.birthday = Date.generateFromAPIFormat(string: json["birthday"].string)
  }

  var serialized: [String: Any] {
    var param: [String: Any] = [:]
    param["height"] = height?.serialized
    param["image"] = image?.serialized
    param["registedAt"] = registedAt?.serialized
    param["clubs"] = clubs?.serialized
    param["weight"] = weight?.serialized
    param["toeicScore"] = toeicScore?.serialized
    param["birthday"] = birthday?.serialized
    return param
  }
}
