/// UserDepartmentEntity.swift
/// generated by jsonschema2swift

import Foundation
import SwiftyJSON


/// user_department
public struct UserDepartmentEntity: EntityType {

  /// 役職名
  enum Role: String {
    case staff = "一般社員"
    case projectGeneralManager = "主査"
    case supervisor = "主任"
    case sectionHead = "係長"
    case chiefEditor = "主幹"
    case secretary = "参事"
    case assistantSectionChief = "課長代理"
    case sectionChief = "課長"
    case assistantGeneralManager = "次長"
    case assistantManager = "部長代理"
    case viceManager = "副部長"
    case manager = "部長"
    case generalManager = "本部長"
    case counselor = "参与"
    case corporateOfficer = "執行役"
    case auditor = "監査役"
    case director = "取締役"
    case vicePresident = "副社長"
    case president = "社長"
    case chairman = "会長"
  }

  /// 役職名
  var role: Role
  /// 部署
  var department: DepartmentEntity

  public init?(json: JSON) {
    guard !json.isEmpty else {
      return nil
    }
    self.role = Role(rawValue: json["role"].string!)!
    self.department = DepartmentEntity(json: json["department"]) as DepartmentEntity!
  }

  var serialized: [String: Any] {
    var param: [String: Any] = [:]
    param["role"] = role.serialized
    param["department"] = department.serialized
    return param
  }
}
